import type { PromptRecord } from './types';

export const SEED_DATA: PromptRecord[] = [
  {
    id: '1',
    title: '生成响应式 SaaS 登录页面',
    goal: '用 React+Tailwind 生成现代风 SaaS 登录页',
    modelUsed: 'GPT-4o',
    scene: 'coding',
    goalClusters: ['前端页面生成'],
    images: [],
    currentVer: 3,
    versions: [
      {
        ver: 1,
        content: '请使用 React 生成一个登录页面。\n\n要求：\n1. 包含邮箱输入、密码、登录按钮\n2. 响应式布局\n\n请直接输出代码。',
        effect: { score: 3, outputContent: '', notes: '基础版本，样式比较简陋，但功能结构是对的。' },
        isStarred: false,
        updatedAt: '2026-04-05T09:00:00Z',
        changeNote: '初版，仅要求生成一个普通的登录表单，样式比较基础。',
      },
      {
        ver: 2,
        content: '你是一位前端工程师。请使用 React 和 Tailwind CSS 实现一个 SaaS 登录页面。\n\n要求：\n1. 包含组件：左侧品牌宣传图/文案，右侧表单区（邮箱、密码、Google 一键登录）\n2. 响应式：移动端自动折叠左侧\n3. 风格：现代简洁\n\n请直接输出可运行的完整代码。',
        effect: { score: 5, outputContent: 'import React from \'react\';\nimport { Mail, Lock, Chrome } from \'lucide-react\';\n\nexport default function LoginPage() {\n  return (\n    <div className="min-h-screen bg-white flex">\n      {/* Brand Panel */}\n      <div className="hidden lg:flex lg:w-1/2 bg-gradient-to-br from-blue-50 to-indigo-100 p-12 flex-col justify-between">\n        <div className="font-bold text-xl">Acme Corp</div>\n        <div>\n          <h1 className="text-4xl font-bold mb-4">Start building today</h1>\n          <p className="text-gray-600">Join thousands of developers.</p>\n        </div>\n        <div className="text-sm text-gray-400">© 2026 Acme Corp</div>\n      </div>\n      {/* Form Panel */}\n      <div className="flex-1 flex items-center justify-center p-8">\n        <form className="w-full max-w-sm space-y-4">\n          <h2 className="text-2xl font-bold">Welcome back</h2>\n          <input type="email" placeholder="Email" className="w-full border rounded-lg px-4 py-3" />\n          <input type="password" placeholder="Password" className="w-full border rounded-lg px-4 py-3" />\n          <button className="w-full bg-black text-white rounded-lg py-3 hover:bg-gray-800 transition">Sign in</button>\n          <button type="button" className="w-full border rounded-lg py-3 flex items-center justify-center gap-2 hover:bg-gray-50 transition"><Chrome size={18}/> Continue with Google</button>\n        </form>\n      </div>\n    </div>\n  );\n}', notes: '增加了响应式的具体要求，但移动端折叠效果还有点生硬。' },
        isStarred: true,
        updatedAt: '2026-04-12T10:15:00Z',
        changeNote: '增加了响应式的具体要求，但移动端折叠效果还有点生硬。',
      },
      {
        ver: 3,
        content: '你是一位精通现代前端设计的工程师。请使用 React 和 Tailwind CSS 实现一个 SaaS 登录页面。\n\n要求：\n1. 风格参考 Linear 和 Vercel，使用大面积留白、细边框和柔和的阴影。\n2. 包含组件：左侧为品牌宣传图/文案，右侧为表单区（邮箱输入、密码、Google 一键登录按钮）。\n3. 响应式：在移动端自动折叠左侧宣传图，表单区居中撑满。\n4. 交互：所有按钮要有明显的 hover 状态和轻微的过渡动画。\n\n请直接输出可运行的完整代码，无需解释。',
        effect: { score: 4, outputContent: 'import React from \'react\';\nimport { Mail, Github } from \'lucide-react\';\n\nexport default function LoginPage() {\n  return (\n    <div className="min-h-screen bg-gray-50 flex">\n      {/* Left Brand Panel */}\n      <div className="hidden lg:flex lg:w-1/2 bg-white border-r border-gray-200 flex-col p-12 justify-between">\n        <div className="flex items-center gap-2 font-bold text-xl">\n          <div className="w-8 h-8 bg-black rounded-lg" /> Acme Corp\n        </div>\n        <div>\n          <h1 className="text-4xl font-bold tracking-tight mb-4">Start building</h1>\n          <p className="text-gray-500 text-lg leading-relaxed">The modern platform for teams who ship fast.</p>\n        </div>\n        <p className="text-sm text-gray-400">© 2026 Acme Corp. All rights reserved.</p>\n      </div>\n      {/* Right Form Panel */}\n      <div className="flex-1 flex items-center justify-center p-8">\n        <div className="w-full max-w-sm">\n          <h2 className="text-2xl font-bold mb-1">Welcome back</h2>\n          <p className="text-gray-500 mb-8">Sign in to your account</p>\n          <form className="space-y-4">\n            <input type="email" placeholder="Email" className="w-full border border-gray-200 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-black/5 focus:border-gray-400 transition" />\n            <input type="password" placeholder="Password" className="w-full border border-gray-200 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-black/5 focus:border-gray-400 transition" />\n            <button className="w-full bg-black text-white rounded-xl py-3 text-sm font-medium hover:bg-gray-800 transition-colors shadow-sm">Sign in</button>\n          </form>\n        </div>\n      </div>\n    </div>\n  );\n}', notes: '这次明确了移动端的折叠逻辑，并且加上了 Linear 风格的描述后，阴影和边框都处理得非常高级，代码直接运行完美适配，不需要二次微调了。' },
        isStarred: false,
        updatedAt: '2026-04-17T14:30:00Z',
        changeNote: '细化了视觉风格描述，增加了对 Linear/Vercel 的明确参考。',
      },
    ],
    createdAt: '2026-04-05T09:00:00Z',
    updatedAt: '2026-04-17T14:30:00Z',
  },
  {
    id: '2',
    title: 'React Hooks 数据获取封装',
    goal: '封装通用的 React 数据获取 Hook，支持 loading/error/retry',
    modelUsed: 'Claude 3.5 Haiku',
    scene: 'coding',
    goalClusters: ['功能代码生成'],
    images: [],
    currentVer: 1,
    versions: [
      {
        ver: 1,
        content: '请写一个通用的 React 自定义 Hook：useFetch。\n\n功能要求：\n1. 传入 URL，返回 { data, loading, error, refetch }\n2. 支持 GET/POST\n3. 内置 abort controller 取消重复请求\n4. 支持 retry 逻辑（最多重试 3 次）\n5. TypeScript 泛型支持\n\n请输出完整的 TypeScript 代码。',
        effect: { score: 3, outputContent: '', notes: '基本功能对了，但 TypeScript 泛型推断有问题，需要手动标注。' },
        isStarred: false,
        updatedAt: '2026-04-15T16:20:00Z',
        changeNote: '初版，基础数据获取 Hook。',
      },
    ],
    createdAt: '2026-04-15T16:20:00Z',
    updatedAt: '2026-04-15T16:20:00Z',
  },
  {
    id: '3',
    title: '解耦 Zustand 状态管理模块',
    goal: '重构现有 Zustand Store，拆分为独立的 slice 模式',
    modelUsed: 'GPT-o3',
    scene: 'coding',
    goalClusters: ['代码重构'],
    images: [],
    currentVer: 2,
    versions: [
      {
        ver: 1,
        content: '我有一个 Zustand store 管理了用户状态、购物车、UI 状态，现在已经 300 多行了。请帮我重构为 slice 模式。\n\n当前代码结构：\n- useStore.ts (所有状态和 actions)\n\n请输出重构后的代码结构和每个文件的代码。',
        effect: { score: 4, outputContent: '', notes: '结构拆分得不错，但 slice 之间的类型互引还需要手动调整。' },
        isStarred: false,
        updatedAt: '2026-04-10T11:00:00Z',
        changeNote: '初版重构方案。',
      },
      {
        ver: 2,
        content: '你是一位 React 状态管理专家。我有一个 Zustand store（300+ 行），需要重构为 slice pattern。\n\n要求：\n1. 拆分为 userSlice / cartSlice / uiSlice\n2. 每个 slice 独立文件，通过 combine 合并\n3. 保持类型安全：slice 之间的 action 可以互相引用\n4. 提供 devtools 中间件配置\n5. 附带迁移指南（从旧 store 迁移到新结构的步骤）\n\n请输出完整代码 + 迁移指南。',
        effect: { score: 5, outputContent: '', notes: '这次加了类型安全和迁移指南的要求后，输出质量大幅提升，基本可以直接用。' },
        isStarred: true,
        updatedAt: '2026-04-10T15:30:00Z',
        changeNote: '强调了类型安全和迁移指南，输出质量大幅提升。',
      },
    ],
    createdAt: '2026-04-10T11:00:00Z',
    updatedAt: '2026-04-10T15:30:00Z',
  },
];
